"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";

import { getReportById } from "../../data";
import StatusBadge from "../../reportcomponents/StatusBadge";

export default function ViewReport() {
  const { id } = useParams();

  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchReport();
  }, []);

  const fetchReport = async () => {
    try {
      const data = await getReportById(id);
      setReport(data);
    } catch (error) {
      console.log(error);
      alert("Report Not Found");
    } finally {
      setLoading(false);
    }
  };

  if (loading) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-slate-100">
        <div className="rounded-2xl bg-white p-10 shadow-xl">
          <h2 className="text-2xl font-semibold text-slate-700">
            Loading Report...
          </h2>
        </div>
      </div>
    );
  }

  if (!report) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-slate-100">
        <div className="rounded-2xl bg-white p-10 text-center shadow-xl">
          <h2 className="text-3xl font-bold text-red-600">Report Not Found</h2>

          <Link
            href="/admin1/report-management"
            className="mt-6 inline-block rounded-xl bg-blue-600 px-6 py-3 text-white hover:bg-blue-700"
          >
            Back
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-slate-100 p-6">
      {/* Header */}

      <div className="mb-8 flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
        <div>
          <h1 className="text-3xl font-bold text-slate-800">Report Details</h1>

          <p className="mt-2 text-slate-500">Complete report information.</p>
        </div>

        <Link
          href="/admin1/report-management"
          className="rounded-xl bg-gray-700 px-5 py-3 text-white hover:bg-gray-800"
        >
          ← Back
        </Link>
      </div>

      {/* Main Card */}

      <div className="overflow-hidden rounded-2xl bg-white shadow-xl">
        {/* Top Banner */}

        <div className="bg-gradient-to-r from-blue-600 via-indigo-600 to-purple-600 p-8 text-white">
          <div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between">
            <div>
              <h2 className="text-4xl font-bold">{report.reportName}</h2>

              <p className="mt-2 text-blue-100">{report.reportType}</p>
            </div>

            <StatusBadge status={report.status} />
          </div>
        </div>

        {/* Information */}

        <div className="grid gap-6 p-8 md:grid-cols-2">
          <Info label="Report Name" value={report.reportName} />

          <Info label="Report Type" value={report.reportType} />

          <Info label="Generated By" value={report.generatedBy} />

          <Info
            label="Created Date"
            value={
              report.createdAt
                ? new Date(report.createdAt).toLocaleString()
                : "-"
            }
          />

          <Info label="Total Records" value={report.totalRecords} />

          <Info label="Generated Time" value={report.generatedTime} />
        </div>

        {/* Summary */}

        <div className="border-t p-8">
          <h3 className="mb-4 text-xl font-bold text-slate-800">
            Report Summary
          </h3>

          <div className="rounded-xl border bg-slate-50 p-5 leading-8">
            {report.summary || "No Summary Available"}
          </div>
        </div>

        {/* Preview */}

        <div className="border-t p-8">
          <h3 className="mb-4 text-xl font-bold text-slate-800">
            Report Preview
          </h3>

          <div className="rounded-xl border bg-white p-6">
            <pre className="overflow-x-auto whitespace-pre-wrap text-sm text-gray-700">
              {JSON.stringify(report.preview || report, null, 2)}
            </pre>
          </div>
        </div>

        {/* Action Buttons */}

        <div className="flex flex-wrap gap-4 border-t p-8">
          <button
            onClick={() => window.print()}
            className="rounded-xl bg-indigo-600 px-6 py-3 font-semibold text-white hover:bg-indigo-700"
          >
            Print Report
          </button>

          <button className="rounded-xl bg-green-600 px-6 py-3 font-semibold text-white hover:bg-green-700">
            Download CSV
          </button>

          <button className="rounded-xl bg-red-600 px-6 py-3 font-semibold text-white hover:bg-red-700">
            Download PDF
          </button>
        </div>
      </div>
    </div>
  );
}

function Info({ label, value }) {
  return (
    <div>
      <p className="mb-2 text-sm font-semibold text-slate-500">{label}</p>

      <div className="rounded-xl border bg-slate-50 p-4 font-medium text-slate-800">
        {value || "-"}
      </div>
    </div>
  );
}
