const express = require("express");
const router = express.Router();

const Report = require("../models/Report");

// ================= Dashboard Summary =================
router.get("/dashboard", async (req, res) => {
  try {
    const totalReports = await Report.countDocuments();

    const generatedReports = await Report.countDocuments({
      status: "Generated",
    });

    const pendingReports = await Report.countDocuments({
      status: "Pending",
    });

    const failedReports = await Report.countDocuments({
      status: "Failed",
    });

    res.status(200).json({
      totalReports,
      generatedReports,
      pendingReports,
      failedReports,

      // Chart Data
      monthlyReports: [
        { month: "Jan", reports: 10 },
        { month: "Feb", reports: 18 },
        { month: "Mar", reports: 25 },
        { month: "Apr", reports: 20 },
        { month: "May", reports: 30 },
        { month: "Jun", reports: 28 },
        { month: "Jul", reports: totalReports },
      ],
    });
  } catch (err) {
    res.status(500).json({
      success: false,
      message: err.message,
    });
  }
});

// ================= Get All Reports =================
router.get("/", async (req, res) => {
  try {
    const reports = await Report.find().sort({ createdAt: -1 });

    res.status(200).json(reports);
  } catch (err) {
    res.status(500).json({
      success: false,
      message: err.message,
    });
  }
});

// ================= Get Report By Id =================
router.get("/:id", async (req, res) => {
  try {
    const report = await Report.findById(req.params.id);

    if (!report) {
      return res.status(404).json({
        success: false,
        message: "Report Not Found",
      });
    }

    res.status(200).json(report);
  } catch (err) {
    res.status(500).json({
      success: false,
      message: err.message,
    });
  }
});

// ================= Export CSV =================
router.get("/export/csv", async (req, res) => {
  try {
    res.status(200).json({
      message: "CSV Export API Ready",
    });
  } catch (err) {
    res.status(500).json({
      success: false,
      message: err.message,
    });
  }
});

// ================= Export PDF =================
router.get("/export/pdf", async (req, res) => {
  try {
    res.status(200).json({
      message: "PDF Export API Ready",
    });
  } catch (err) {
    res.status(500).json({
      success: false,
      message: err.message,
    });
  }
});

// ================= Generate Report =================
router.post("/generate", async (req, res) => {
  try {
    const {
      reportName,
      reportType,
      generatedBy,
      fromDate,
      toDate,
      totalRecords,
      status,
      summary,
      preview,
      fileName,
      fileType,
      generatedTime,
    } = req.body;

    // Validation
    if (!reportName || !reportType || !generatedBy || !fromDate || !toDate) {
      return res.status(400).json({
        success: false,
        message:
          "Report Name, Report Type, Generated By, From Date and To Date are required.",
      });
    }

    const report = new Report({
      reportName,
      reportType,
      generatedBy,
      fromDate,
      toDate,
      totalRecords,
      status,
      summary,
      preview,
      fileName,
      fileType,
      generatedTime,
    });

    await report.save();

    res.status(201).json({
      success: true,
      message: "Report Generated Successfully",
      data: report,
    });
  } catch (error) {
    console.error(error);

    res.status(500).json({
      success: false,
      message: "Internal Server Error",
      error: error.message,
    });
  }
});

module.exports = router;
