const express = require("express");
const router = express.Router();

const Report = require("../models/Report");
const Leads = require("../models/Leads");
const Client = require("../models/Client");
const User = require("../models/User");
const Project = require("../models/Project");
const Invoice = require("../models/Invoice");
const Task = require("../models/Task");

// ================= Dashboard Summary =================
router.get("/dashboard", async (req, res) => {
  try {
    const totalReports = await Report.countDocuments();

    const generatedReports = await Report.countDocuments({
      status: "Generated",
    });

    const pendingReports = await Report.countDocuments({
      status: "Pending",
    });

    const failedReports = await Report.countDocuments({
      status: "Failed",
    });

    res.status(200).json({
      totalReports,
      generatedReports,
      pendingReports,
      failedReports,

      // Chart Data
      monthlyReports: [
        { month: "Jan", reports: 10 },
        { month: "Feb", reports: 18 },
        { month: "Mar", reports: 25 },
        { month: "Apr", reports: 20 },
        { month: "May", reports: 30 },
        { month: "Jun", reports: 28 },
        { month: "Jul", reports: totalReports },
      ],
    });
  } catch (err) {
    res.status(500).json({
      success: false,
      message: err.message,
    });
  }
});

// ================= Get All Reports =================
router.get("/", async (req, res) => {
  try {
    const reports = await Report.find().sort({ createdAt: -1 });

    res.status(200).json(reports);
  } catch (err) {
    res.status(500).json({
      success: false,
      message: err.message,
    });
  }
});

// ================= Get Report By Id =================
router.get("/:id", async (req, res) => {
  try {
    const report = await Report.findById(req.params.id);

    if (!report) {
      return res.status(404).json({
        success: false,
        message: "Report Not Found",
      });
    }

    res.status(200).json(report);
  } catch (err) {
    res.status(500).json({
      success: false,
      message: err.message,
    });
  }
});

// ================= Export CSV =================
router.get("/export/csv", async (req, res) => {
  try {
    res.status(200).json({
      message: "CSV Export API Ready",
    });
  } catch (err) {
    res.status(500).json({
      success: false,
      message: err.message,
    });
  }
});

// ================= Export PDF =================
router.get("/export/pdf", async (req, res) => {
  try {
    res.status(200).json({
      message: "PDF Export API Ready",
    });
  } catch (err) {
    res.status(500).json({
      success: false,
      message: err.message,
    });
  }
});

// ================= Generate Report =================
router.post("/generate", async (req, res) => {
  try {
    const {
      reportName,
      reportType,
      generatedBy,
      fromDate,
      toDate,
      fileType,
    } = req.body;

    // Validation
    if (!reportName || !reportType || !generatedBy || !fromDate || !toDate) {
      return res.status(400).json({
        success: false,
        message:
          "Report Name, Report Type, Generated By, From Date and To Date are required.",
      });
    }

    const queryStartTime = Date.now();

    // Map the report type to a Mongoose model
    let Model = null;
    let normalizedType = reportType;

    if (reportType === "Lead Report" || reportType === "Leads") {
      Model = Leads;
      normalizedType = "Lead Report";
    } else if (reportType === "Client Report" || reportType === "Clients") {
      Model = Client;
      normalizedType = "Client Report";
    } else if (reportType === "Employee Report" || reportType === "Employees" || reportType === "Users") {
      Model = User;
      normalizedType = "Employee Report";
    } else if (reportType === "Project Report" || reportType === "Projects") {
      Model = Project;
      normalizedType = "Project Report";
    } else if (reportType === "Revenue Report" || reportType === "Invoices" || reportType === "Sales") {
      Model = Invoice;
      normalizedType = "Revenue Report";
    } else if (reportType === "Task Report" || reportType === "Tasks") {
      Model = Task;
      normalizedType = "Task Report";
    }

    let matchingRecords = [];
    if (Model) {
      const start = new Date(fromDate);
      const end = new Date(toDate);
      end.setHours(23, 59, 59, 999);

      // Query database based on createdAt timestamps within dates range
      matchingRecords = await Model.find({
        createdAt: { $gte: start, $lte: end },
      }).lean();
    }

    const totalRecords = matchingRecords.length;
    const preview = matchingRecords.slice(0, 20); // Save the first 20 records as preview
    const queryDuration = ((Date.now() - queryStartTime) / 1000).toFixed(2) + "s";

    const summary = `This report details the activity metrics for the ${normalizedType} module during the period from ${fromDate} to ${toDate}. A total of ${totalRecords} record(s) were found and compiled successfully.`;
    const finalFileName = `${reportName.toLowerCase().replace(/\s+/g, "_")}_report.${(fileType || "CSV").toLowerCase()}`;

    const report = new Report({
      reportName,
      reportType: normalizedType,
      generatedBy,
      fromDate,
      toDate,
      totalRecords,
      status: "Generated",
      summary,
      preview,
      fileName: finalFileName,
      fileType: fileType || "CSV",
      generatedTime: queryDuration,
    });

    await report.save();

    res.status(201).json({
      success: true,
      message: "Report Generated Successfully",
      data: report,
    });
  } catch (error) {
    console.error(error);

    res.status(500).json({
      success: false,
      message: "Internal Server Error",
      error: error.message,
    });
  }
});

module.exports = router;
